### PR TITLE
netron-ha-tool: reduce term_disabled block

### PR DESCRIPTION
**Pull request by AbelNavarro**
It has been found that some operations during the router migration can
take long time. This sometimes causes Pacemaker to believe the service
is unresponsive and tries to terminate it (SIGTERM). The behavior until
now was to block such SIGTERM signals during the router migration and
the long wait_for_router_migrated. When Pacemaker cannot terminate the
process it usually fences the node.

By reducing the scope where the SIGTERM is prevented we want to give
more chances for Pacemaker to gracefully terminate neutron-ha-tool
service.

Reference: https://bugzilla.suse.com/show_bug.cgi?id=1059530

### CODE REVIEW

**Comment by AbelNavarro** [comment]
[Make neutron-l3-ha-service respond to TERM signal as quickly as possible](https://trello.com/c/O2sWBMIc/142-make-neutron-l3-ha-service-respond-to-term-signal-as-quickly-as-possible)

**Review by matelakat — APPROVED** [review]

**Review by nicolasbock — CHANGES_REQUESTED** [review]
If I understand this correctly then this change reduces the size of the protected code block and exposes more code to a SIGTERM. But doesn't that defeat the original intent of disabling SIGTERM around the `migrate_router` call? Why is it ok to expose parts of the function now?

**Comment by AbelNavarro** [comment]
@nicolasbock we are under the assumption that `wait_router_migrated` is probably the function that takes more time in that loop. That function was probably needed because otherwise you can pile up a batch of router creations/deletions and never check whether they are online. See the original commit by @rhafer regarding this: https://github.com/abel-navarro/cookbook-openstack-network/commit/f8e925c21ba83ba37c77aa4907d0137bbb4f97ef

So, waiting for routers should improve performance, but shouldn't change the database state, since that is done in the functions that we don't allow to SIGTERM. Waiting for routers is still observed and the performance gains remain. We do allow now to interrupt that part in order to make Pacemaker happier.

**Review by nicolasbock — APPROVED** [review]
Cool, thanks for the explanation @abel-navarro! That makes sense. Thanks!

**Pull request merged**
